### ISSUE TITLE
Feature points finalisation

### ISSUE THREAD

**Issue by andrewbutterfield** [RobAntcliff/Matte_Group_Proj#2]

**Comment by andrewbutterfield** [comment]
Apologies for not raising this formally earlier. I'll post your final estimates here shortly.

**Comment by andrewbutterfield** [comment]
Here is your feature list

[R1-G7-Points.xlsx](https://github.com/RobAntcliff/Matte_Group_Proj/files/770801/R1-G7-Points.xlsx)

**Comment by RobAntcliff** [comment]
Thanks!
