### ISSUE TITLE
Iteration 3 Feedback

### ISSUE THREAD

**Issue by andrewbutterfield** [RobAntcliff/Matte_Group_Proj#3]
# Group 7 - Iteration 3 - Feedback

## Installation

Installation/testing is fine

No description given of which dependencies are unchanged, which are new since Iteration 2

### PML File Selection

Still the issue with File-Selector, and misspelling of py file name
 - please proof-read and edit as appropriate.

Why the ' ' around the filename? The prompt doesn't say this is required. This should be changed so the user does not have to use the single quotes. 

Why isn't the test file in the File-Selector folder? Alternatively why doesn't the app cd into a directory with test files to begin?

Also, be very specific about which file should be chosen.
This applies also to the number item 1 that occurs after 1 and 2,
about test_selection. What do you mean by a "verified" PML file?

### Load Owl Ontology

Number 2 should be part of installation above, not part of a feature test. Also, set it up so I don't have to confirm anything at the command line.

Please have the relevant OWL files nearby and tell me which ones to use in a specific test for a specific feature.

When I try with DINTO_1_2.owl I get the following, which doesn't look too good

```
butrfeld@CS4098:~/CS4098/Matte_Group_Proj/OWL/DINTO/DINTO1.2$ ontospy DINTO_1.2.owl
Setup successfull: local library created at </home/butrfeld/.ontospy/models/>
OntoSpy v1.7.4
------------
You passed the arguments:
-> <DINTO_1.2.owl>
WARNING:rdflib.term:file:///home/butrfeld/CS4098/Matte_Group_Proj/OWL/DINTO/DINTO1.2/?xml version="1.0"? does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:!DOCTYPE Ontology [
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#"  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:!ENTITY xml "http://www.w3.org/XML/1998/namespace"  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:file:///home/butrfeld/CS4098/Matte_Group_Proj/OWL/DINTO/DINTO1.2/?xml version="1.0"? does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:!DOCTYPE Ontology [
    <!ENTITY xsd "http://www.w3.org/2001/XMLSchema#"  does not look like a valid URI, trying to serialize this will break.
WARNING:rdflib.term:!ENTITY xml "http://www.w3.org/XML/1998/namespace"  does not look like a valid URI, trying to serialize this will break.
/usr/local/lib/python2.7/dist-packages/rdflib/plugins/parsers/structureddata.py:30: UserWarning: html5lib not found! RDFa and Microdata parsers will not be available.
  'parsers will not be available.')
----------
Fatal error parsing graph (tried using RDF serialization: ['xml', 'turtle', 'n3', 'nt', 'trix', 'rdfa'])

----------
TIP: You can try one of the following RDF validation services
<http://mowl-power.cs.man.ac.uk:8080/validator/validate>
<http://www.ivan-herman.net/Misc/2008/owlrl/>

----------
Time:	   6.81s
butrfeld@CS4098:/CS4098/Matte_Group_Proj/OWL/DINTO/DINTO1.2$ 
```

### PML Log-file Generation

More inconsistent item numbering !

This feature should be above the DINTO/OWL ones. Also, why is is seperate from the file selection feature?

In fact the file-selection feature seems to do this anyway so why have a seperate program to test it?

## Conceptual Integrity

This is completely lacking here - you need to glue these pieces together into a coherent whole.

Only 3 features working at this stage?

You also need to move away from this jumping to different directories to test/use different features. All features should be accessible from a single "place". Think 'conceptual integrity'.

**Comment by RobAntcliff** [comment]
Thanks for the feedback Dr. Butterfield. We will have this all cleaned up and ready for release 1. 

Also, for release one, are our feature points being changed or are they staying the same?

**Comment by andrewbutterfield** [comment]
Revised feature points attached (fbinfer is off the table !)

[R1-G7-Points-v2.xlsx](https://github.com/RobAntcliff/Matte_Group_Proj/files/828350/R1-G7-Points-v2.xlsx)

**Comment by RobAntcliff** [comment]
Great, thanks!
