### ISSUE TITLE
Release 2 Feature Points

### ISSUE THREAD

**Issue by RobAntcliff** [RobAntcliff/Matte_Group_Proj#4]
[Release-2-Bidding.xlsx](https://github.com/RobAntcliff/Matte_Group_Proj/files/853266/Release-2-Bidding.xlsx)

**Comment by RobAntcliff** [comment]
Note: I wanted to upload it in .csv but it would only let me add it in .xlsx format. Please let me know if you'd like me to send you a different file type.

**Comment by andrewbutterfield** [comment]
The mock DDI is simply some file which is a list of quadruples of the form

 ( drug1, drug2,   good/bad, time )

So, given two drugs you can see if (1) they have an interaction, and if so, if it is good or bad, and the size of the time-window in which the interaction occurs. That's all

The precise file/DB-format is entirely up to you

I'll describe some test data in a neutral text format, and you pour it into your own.

Please revisit your bids - and remove the 'budget' data  - it's wrong. Just bid the way you did for Release 1.

**Comment by andrewbutterfield** [comment]
Here is the bid spreadsheet as of the end of our meeting today - please revise bids or not, as you see fit, and then let me know...

[G7-Release-2-Backlog.xlsx](https://github.com/RobAntcliff/Matte_Group_Proj/files/862406/G7-Release-2-Backlog.xlsx)

**Comment by andrewbutterfield** [comment]
Happy with the bids as they stand?

**Comment by aislingnorris** [comment]
We revised, and these are our final points

[G7-Release-2-Backlog.xlsx](https://github.com/RobAntcliff/Matte_Group_Proj/files/864282/G7-Release-2-Backlog.xlsx)

**Comment by andrewbutterfield** [comment]
You have done something funny with the spreadsheet - I see gridlines only in columns A-J, and lines 1-42. I can't make the gridlines elsewhere become visible - I need to add extra stuff to the right and below of your stuff. Can you fix this and re-submit please?

**Comment by aislingnorris** [comment]
Sorry, Numbers on mac likes to remove empty columns.
This should be fixed.
[G7-Release-2-Backlog.xlsx](https://github.com/RobAntcliff/Matte_Group_Proj/files/864391/G7-Release-2-Backlog.xlsx)

**Comment by andrewbutterfield** [comment]
Perfect - thanks !  (I'm using Excel on a Mac, just to be awkward....)

**Comment by andrewbutterfield** [comment]
Do you really need 45 points to implement two features that lookup drug pairs from data stored in a csv file?

**Comment by andrewbutterfield** [comment]
55 points to find and locate a construct without a name? You can already parse PML, based on Release 1 features/

**Comment by aislingnorris** [comment]
No sorry, we forgot to reduce those from the previous estimate before seeing the mock. 5 for either of those it should be.
The construct is 55 as you advised yesterday to add the parser feature estimate we had into that, as our parser is not complete, it only searches a PML for drugs from a dictionary right now, we have no time handling in it.

**Comment by andrewbutterfield** [comment]
Time handling is introduced by other features, like on rows 16, 20, 21,....  Firuring out how to identify drugs in PML is on row 5 with a bid. So this feature in row 9 simply requires basic/standard PML parsing to work. The extra parsing work required to have drugs or timing should be associated with those other features. Can you have a quick discussion on this in the group? Thanks

**Comment by aislingnorris** [comment]
We have updated the points to spread out as you said, and fixed the file loading to the correct points [G7-Release-2-Backlog.xlsx](https://github.com/RobAntcliff/Matte_Group_Proj/files/864989/G7-Release-2-Backlog.xlsx)

**Comment by andrewbutterfield** [comment]
150 to merge clinical pathways?

file one:    `process P1 {p1 stuff}`
file two:    `process P2 {p2 stuff}`
merged file `process NewName1 {branch newName2 { sequence P1{p1 stuff} ; sequence P2 {p2 stuff} }} `

**Comment by andrewbutterfield** [comment]
This feature depends on PML-TX Save to File to produce the final file.
All this feature is really is a function that takes two PML ASTs as input an returns
a new one as shown above.
This feature does not include the parsing of PML files as that is done elsewhere, nor the outupt of the result as just explained.

**Comment by RobAntcliff** [comment]
[G7-Release-2-Backlog (1).xlsx](https://github.com/RobAntcliff/Matte_Group_Proj/files/865435/G7-Release-2-Backlog.1.xlsx)

I changed the "Merge Clinical Pathways" Estimate.

**Comment by andrewbutterfield** [comment]
Here are my "purchases". Any last comments?
[G7-Release-2-Backlog.xlsx](https://github.com/RobAntcliff/Matte_Group_Proj/files/865481/G7-Release-2-Backlog.xlsx)

**Comment by RobAntcliff** [comment]
Perfect, thanks!
